version: '3.8'
services:
  cs-subscribe-apigateway-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/app/apigateway
    tty: true
    working_dir: /app/apigateway
    networks:
      - cs-subscribe

networks:
  cs-subscribe:
    external: true

